server:
  port: 5050
  servlet-path: /

spring:
  application:
    name: e-auction-seller-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/eauctiondb-seller?retryWrites=true&w=majority
  cloud:
    inetutils:
      ignoredInterfaces: eth0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


info:
  app:
    name: ${spring.application.name}
  build:
    version: ${project.version}

app:
  clients:
    web-client:
      host: http://localhost:3000
  services:
    buyer-service:
      scheme: http
      host: localhost
      port: 6060
      bid-search: /e-auction/api/v1/buyer/show-bids/{productId}
